// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNrbJmGB2HYk0jTeg2w-IgaIDHrlq5pec',
    appId: '1:672851198600:web:9e8dbb63d3d8b8ce31d53d',
    messagingSenderId: '672851198600',
    projectId: 'myecommerce-e1e31',
    authDomain: 'myecommerce-e1e31.firebaseapp.com',
    storageBucket: 'myecommerce-e1e31.firebasestorage.app',
    measurementId: 'G-RMXGE7DYDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6r9EjaDxmJbv1My6n2ft8rkLgUfpDpIo',
    appId: '1:672851198600:android:81c6fef5f1ead33631d53d',
    messagingSenderId: '672851198600',
    projectId: 'myecommerce-e1e31',
    storageBucket: 'myecommerce-e1e31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnMSlvfr3F6xAiRkZQYPLnL2YC7MBIJ-c',
    appId: '1:672851198600:ios:ded087f8b66c877b31d53d',
    messagingSenderId: '672851198600',
    projectId: 'myecommerce-e1e31',
    storageBucket: 'myecommerce-e1e31.firebasestorage.app',
    iosBundleId: 'com.example.myecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnMSlvfr3F6xAiRkZQYPLnL2YC7MBIJ-c',
    appId: '1:672851198600:ios:ded087f8b66c877b31d53d',
    messagingSenderId: '672851198600',
    projectId: 'myecommerce-e1e31',
    storageBucket: 'myecommerce-e1e31.firebasestorage.app',
    iosBundleId: 'com.example.myecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNrbJmGB2HYk0jTeg2w-IgaIDHrlq5pec',
    appId: '1:672851198600:web:12685c70de39132c31d53d',
    messagingSenderId: '672851198600',
    projectId: 'myecommerce-e1e31',
    authDomain: 'myecommerce-e1e31.firebaseapp.com',
    storageBucket: 'myecommerce-e1e31.firebasestorage.app',
    measurementId: 'G-8C4N0LXY6L',
  );
}
